server {
    listen 80;
    server_name _;
    absolute_redirect off;
    client_max_body_size 0;

    location /images/ {
        alias /data/images/;
    }

    location /diag/ {
        alias /data/diag/;
    }

    location /boot/ {
        proxy_pass http://console:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_read_timeout 300s;
    }

    location = / {
        return 302 http://$host:43123/;
    }
}
